Changed Mullvad Configuration

diff --git a/file_roots/gateway/etc/init.d/batadv-vis b/file_roots/gateway/etc/init.d/batadv-vis
--- a/file_roots/gateway/etc/init.d/batadv-vis
+++ b/file_roots/gateway/etc/init.d/batadv-vis
@@ -23,11 +23,11 @@ BATADV_VIS_DEFAULT="${BATADV_VIS_DEFAULT:-/etc/default/alfred}"
 
 # It is not safe to start if we don't have a default configuration...
 if [ ! -f "$BATADV_VIS_DEFAULT" ]; then
-        echo "$BATADV_VIS_DEFAULT does not exist! - Aborting..."
-        if [ "$BATADV_VIS_DEFAULT" = "/etc/default/alfred" ]; then
-                echo "Run 'salt' to fix the problem."
-        fi
-        exit 0
+    echo "$BATADV_VIS_DEFAULT does not exist! - Aborting..."
+    if [ "$BATADV_VIS_DEFAULT" = "/etc/default/alfred" ]; then
+        echo "Run 'salt' to fix the problem."
+    fi
+    exit 0
 fi
 
 . /lib/lsb/init-functions
@@ -56,48 +56,48 @@ check_status()
 }
 
 case "$1" in
-        start)
-                test_config
-                if [ -e "$BATADV_VIS_PID" ]; then
-                        log_failure_msg "batadv-vis service already running (pid file $BATADV_VIS_PID currenty exists)"
-                        exit 1
-                fi
-                log_daemon_msg "Starting $DESC" "$NAME"
-                start-stop-daemon --start --quiet --pidfile "$BATADV_VIS_PID" \
-                        --exec /usr/bin/batadv-vis -i ${BATMANIF} -u ${UNIX_SOCKET} -s
-                sleep 2
+    start)
+        test_config
+        if [ -e "$BATADV_VIS_PID" ]; then
+            log_failure_msg "batadv-vis service already running (pid file $BATADV_VIS_PID currenty exists)"
+            exit 1
+        fi
+        log_daemon_msg "Starting $DESC" "$NAME"
+        start-stop-daemon --start --quiet --pidfile "$BATADV_VIS_PID" \
+            --exec /usr/bin/batadv-vis -i ${BATMANIF} -u ${UNIX_SOCKET} -s
+        sleep 2
 
-                if check_status -q; then
-                        log_end_msg 0
-                else
-                        log_failure_msg "check syslog for diagnostics."
-                        log_end_msg 1
-                        exit 1
-                fi
-                ;;
-        stop)
-                log_daemon_msg "Stopping $DESC" "$NAME"
-                start-stop-daemon --stop --quiet --pidfile "$BATADV_VIS_PID"
-                log_end_msg $?
-                rm -f "$BATADV_VIS_PID"
-                ;;
-        restart | force-reload)
-                test_config
-                $0 stop
-                sleep 2
-                $0 start
-                if [ "$?" != "0" ]; then
-                        exit 1
-                fi
-                ;;
-        status)
-                echo -n "Status of $DESC: "
-                check_status -v
-                exit "$?"
-                ;;
-        *)
-                echo "Usage: $0 {start|stop|restart|force-reload|status}"
+        if check_status -q; then
+            log_end_msg 0
+        else
+            log_failure_msg "check syslog for diagnostics."
+            log_end_msg 1
+            exit 1
+        fi
+        ;;
+    stop)
+        log_daemon_msg "Stopping $DESC" "$NAME"
+        start-stop-daemon --stop --quiet --pidfile "$BATADV_VIS_PID"
+        log_end_msg $?
+        rm -f "$BATADV_VIS_PID"
+        ;;
+    restart | force-reload)
+        test_config
+        $0 stop
+        sleep 2
+        $0 start
+        if [ "$?" != "0" ]; then
                 exit 1
+        fi
+        ;;
+    status)
+        echo -n "Status of $DESC: "
+        check_status -v
+        exit "$?"
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart|force-reload|status}"
+        exit 1
 esac
 
 exit 0
diff --git a/file_roots/gateway/etc/init.d/isc-dhcp6-server b/file_roots/gateway/etc/init.d/isc-dhcp6-server
--- a/file_roots/gateway/etc/init.d/isc-dhcp6-server
+++ b/file_roots/gateway/etc/init.d/isc-dhcp6-server
@@ -23,11 +23,11 @@ DHCPD_DEFAULT="${DHCPD_DEFAULT:-/etc/default/isc-dhcp6-server}"
 
 # It is not safe to start if we don't have a default configuration...
 if [ ! -f "$DHCPD_DEFAULT" ]; then
-        echo "$DHCPD_DEFAULT does not exist! - Aborting..."
-        if [ "$DHCPD_DEFAULT" = "/etc/default/isc-dhcp6-server" ]; then
-                echo "Run 'dpkg-reconfigure isc-dhcp-server' to fix the problem."
-        fi
-        exit 0
+    echo "$DHCPD_DEFAULT does not exist! - Aborting..."
+    if [ "$DHCPD_DEFAULT" = "/etc/default/isc-dhcp6-server" ]; then
+        echo "Run 'dpkg-reconfigure isc-dhcp-server' to fix the problem."
+    fi
+    exit 0
 fi
 
 . /lib/lsb/init-functions
@@ -47,13 +47,13 @@ DHCPD_PID="${DHCPD_PID:-/var/run/dhcpd6.pid}"
 
 test_config()
 {
-        if ! /usr/sbin/dhcpd -6 -t $OPTIONS -q -cf "$DHCPD_CONF" > /dev/null 2>&1; then
-                echo "dhcpd self-test failed. Please fix $DHCPD_CONF."
-                echo "The error was: "
-                /usr/sbin/dhcpd -6 -t $OPTIONS -cf "$DHCPD_CONF"
-                exit 1
-        fi
-        touch /var/lib/dhcp/dhcpd6.leases
+    if ! /usr/sbin/dhcpd -6 -t $OPTIONS -q -cf "$DHCPD_CONF" > /dev/null 2>&1; then
+        echo "dhcpd self-test failed. Please fix $DHCPD_CONF."
+        echo "The error was: "
+        /usr/sbin/dhcpd -6 -t $OPTIONS -cf "$DHCPD_CONF"
+        exit 1
+    fi
+    touch /var/lib/dhcp/dhcpd6.leases
 }
 
 # single arg is -v for messages, -q for none
@@ -73,49 +73,49 @@ check_status()
 }
 
 case "$1" in
-        start)
-                test_config
-                if [ -e "$DHCPD_PID" ]; then
-                        log_failure_msg "dhcpd service already running (pid file $DHCPD_PID currenty exists)"
-                        exit 1
-                fi
-                log_daemon_msg "Starting $DESC" "$NAME"
-                start-stop-daemon --start --quiet --pidfile "$DHCPD_PID" \
-                        --exec /usr/sbin/dhcpd -- \
-                        -6 -q $OPTIONS -cf "$DHCPD_CONF" -pf "$DHCPD_PID" $INTERFACES
-                sleep 2
+    start)
+        test_config
+        if [ -e "$DHCPD_PID" ]; then
+            log_failure_msg "dhcpd service already running (pid file $DHCPD_PID currenty exists)"
+            exit 1
+        fi
+        log_daemon_msg "Starting $DESC" "$NAME"
+        start-stop-daemon --start --quiet --pidfile "$DHCPD_PID" \
+            --exec /usr/sbin/dhcpd -- \
+            -6 -q $OPTIONS -cf "$DHCPD_CONF" -pf "$DHCPD_PID" $INTERFACES
+        sleep 2
 
-                if check_status -q; then
-                        log_end_msg 0
-                else
-                        log_failure_msg "check syslog for diagnostics."
-                        log_end_msg 1
-                        exit 1
-                fi
-                ;;
-        stop)
-                log_daemon_msg "Stopping $DESC" "$NAME"
-                start-stop-daemon --stop --quiet --pidfile "$DHCPD_PID"
-                log_end_msg $?
-                rm -f "$DHCPD_PID"
-                ;;
-        restart | force-reload)
-                test_config
-                $0 stop
-                sleep 2
-                $0 start
-                if [ "$?" != "0" ]; then
-                        exit 1
-                fi
-                ;;
-        status)
-                echo -n "Status of $DESC: "
-                check_status -v
-                exit "$?"
-                ;;
-        *)
-                echo "Usage: $0 {start|stop|restart|force-reload|status}"
-                exit 1
+        if check_status -q; then
+            log_end_msg 0
+        else
+            log_failure_msg "check syslog for diagnostics."
+            log_end_msg 1
+            exit 1
+        fi
+        ;;
+    stop)
+        log_daemon_msg "Stopping $DESC" "$NAME"
+        start-stop-daemon --stop --quiet --pidfile "$DHCPD_PID"
+        log_end_msg $?
+        rm -f "$DHCPD_PID"
+        ;;
+    restart | force-reload)
+        test_config
+        $0 stop
+        sleep 2
+        $0 start
+        if [ "$?" != "0" ]; then
+            exit 1
+        fi
+        ;;
+    status)
+        echo -n "Status of $DESC: "
+        check_status -v
+        exit "$?"
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart|force-reload|status}"
+        exit 1
 esac
 
 exit 0
